package com.example.jalase41

object City {
/*    val listCity = arrayListOf<String>(
        "Tehran",
        "Tehran",
        "Tehran",
        "Karaj",
        "Karaj",
        "Karaj",
        "Karaj",
        "Karaj",
        "Karaj",
        "Shiraz",
        "Shiraz",
        "Shiraz",
        "Shiraz",
        "Shiraz",
        "Shiraz",
        "Shiraz",
        "Shiraz",
        "Shiraz",
        "Shiraz",
        "Shiraz",
        "Shiraz",
        "Shiraz",
        "Ardebil",
        "Mashhad",
        "Mashhad",
        "Mashhad",
        "Mashhad",
        "Qom",
        "Tehran",
        "Tehran",
        "Tehran",
        "Karaj",
        "Karaj",
        "Karaj",
        "Karaj",
        "Karaj",
        "Karaj",
        "Shiraz",
        "Shiraz",
        "Shiraz",
        "Shiraz",
        "Shiraz",
        "Shiraz",
        "Shiraz",
        "Shiraz",
        "Shiraz",
        "Shiraz",
        "Shiraz",
        "Shiraz",
        "Shiraz",
        "Ardebil",
        "Mashhad",
        "Mashhad",
        "Mashhad",
        "Mashhad",
        "Qom"
    )*/

    val listCity = arrayListOf<CityDataClass>(
        CityDataClass(1, "Mashad", "مشهد زیباست"),
        CityDataClass(2, "Tehran", "تهران زیباست"),
        CityDataClass(3, "Karaj", "کرج زیباست"),
        CityDataClass(4, "Shiraz", "شیراز زیباست"),
        CityDataClass(5, "Tabriz", "تبریز زیباست"),
        CityDataClass(6, "Qom", "قم زیباست"),
        CityDataClass(7, "Ardebil", "اردبیل زیباست")
    )
}